name: .NET Core Build and Release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x'

    - name: Build the project with dotnet msbuild
      run: |
        dotnet msbuild UnpackMiColorFace.sln /t:Restore /p:Configuration=Release
        dotnet msbuild UnpackMiColorFace.sln /t:Build /p:Configuration=Release /p:OutputPath=./output

    - name: 制作UnpackMiColorFace.tar.gz
      run: |
        tar czf UnpackMiColorFace.tar.gz output

    - name: Publish Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          output.tar.gz
        tag_name: "UnpackMiColorFace"
        token: ${{ secrets.AA_TOKEN }}
        body: |
          #UnpackMiColorFace解包程序
